### ISSUE TITLE
qual o comando para ativar anti número gringo (internacional)?

### ISSUE THREAD

**Issue by dionesankh** [NuevaGeneracionALB/aleatory-md#19]

**Comment by Shshhssjsjjeje** [comment]
[*] Grimler's (NL) mirrors selected
    Changing main repository
[*] Running apt update
Get:1 https://grimler.se/termux-packages-24 stable InRelease [14.0 kB]
Get:2 https://grimler.se/termux-packages-24 stable/main arm Packages [487 kB]
Fetched 501 kB in 5s (91.2 kB/s)
Reading package lists... Done
Building dependency tree... Done
60 packages can be upgraded. Run 'apt list --upgradable' to see them.
~ $ apt-get upgrade
Reading package lists... Done
Building dependency tree... Done
Calculating upgrade... Done
The following packages have been kept back:
  apt dpkg libgnutls unbound util-linux
The following packages will be upgraded:
  bash ca-certificates command-not-found coreutils curl
  dash debianutils dialog diffutils dos2unix ed findutils
  gawk gpgv grep gzip inetutils less libandroid-support
  libassuan libc++ libcurl libevent libexpat libgcrypt
  libgmp libgpg-error libiconv libidn2 liblz4 liblzma
  libmpfr libnettle libnghttp2 libssh2 libtirpc
  libunistring lsof nano ncurses openssl pcre2 procps
  psmisc readline sed tar termux-am-socket termux-keyring
  termux-licenses termux-tools unzip xxhash xz-utils zlib
55 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
Need to get 13.4 MB of archives.
After this operation, 2154 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://grimler.se/termux-packages-24 stable/main arm libiconv arm 1.17 [550 kB]
Get:2 https://grimler.se/termux-packages-24 stable/main arm libandroid-support arm 28-3 [10.2 kB]
Get:3 https://grimler.se/termux-packages-24 stable/main arm ncurses arm 6.4.20230527 [502 kB]
Get:4 https://grimler.se/termux-packages-24 stable/main arm readline arm 8.2.1 [224 kB]
Get:5 https://grimler.se/termux-packages-24 stable/main arm termux-am-socket arm 1.5.0 [10.4 kB]
Get:6 https://grimler.se/termux-packages-24 stable/main arm libc++ arm 25c [185 kB]
Get:7 https://grimler.se/termux-packages-24 stable/main arm libgmp arm 6.2.1-2 [295 kB]
Get:8 https://grimler.se/termux-packages-24 stable/main arm coreutils arm 9.3 [744 kB]
Get:9 https://grimler.se/termux-packages-24 stable/main arm ca-certificates all 1:2023.05.30 [118 kB]
Get:10 https://grimler.se/termux-packages-24 stable/main arm zlib arm 1.2.13 [61.2 kB]
Get:11 https://grimler.se/termux-packages-24 stable/main arm openssl arm 1:3.1.2 [1511 kB]
Get:12 https://grimler.se/termux-packages-24 stable/main arm libnghttp2 arm 1.55.1 [90.7 kB]
Get:13 https://grimler.se/termux-packages-24 stable/main arm libssh2 arm 1.11.0 [192 kB]
Get:14 https://grimler.se/termux-packages-24 stable/main arm libcurl arm 8.2.1 [978 kB]
Get:15 https://grimler.se/termux-packages-24 stable/main arm curl arm 8.2.1 [193 kB]
Get:16 https://grimler.se/termux-packages-24 stable/main arm dash arm 0.5.12 [61.5 kB]
Get:17 https://grimler.se/termux-packages-24 stable/main arm diffutils arm 3.10 [147 kB]
Get:18 https://grimler.se/termux-packages-24 stable/main arm findutils arm 4.9.0-2 [229 kB]
Get:19 https://grimler.se/termux-packages-24 stable/main arm libmpfr arm 4.2.0-p9-0 [263 kB]
Get:20 https://grimler.se/termux-packages-24 stable/main arm gawk arm 5.2.2 [760 kB]
Get:21 https://grimler.se/termux-packages-24 stable/main arm pcre2 arm 10.42 [848 kB]
Get:22 https://grimler.se/termux-packages-24 stable/main arm grep arm 3.11 [116 kB]
Get:23 https://grimler.se/termux-packages-24 stable/main arm gzip arm 1.12-1 [72.2 kB]
Get:24 https://grimler.se/termux-packages-24 stable/main arm less arm 633-1 [100.0 kB]
Get:25 https://grimler.se/termux-packages-24 stable/main arm procps arm 3.3.17-2 [131 kB]
Get:26 https://grimler.se/termux-packages-24 stable/main arm psmisc arm 23.6-1 [38.5 kB]
Get:27 https://grimler.se/termux-packages-24 stable/main arm sed arm 4.9-1 [111 kB]
Get:28 https://grimler.se/termux-packages-24 stable/main arm tar arm 1.35 [328 kB]
Get:29 https://grimler.se/termux-packages-24 stable/main arm liblzma arm 5.4.4 [241 kB]
Get:30 https://grimler.se/termux-packages-24 stable/main arm xz-utils arm 5.4.4 [62.3 kB]
Get:31 https://grimler.se/termux-packages-24 stable/main arm dialog arm 1.3-20230209-0 [92.4 kB]
Get:32 https://grimler.se/termux-packages-24 stable/main arm termux-tools all 1.38.5 [28.8 kB]
Get:33 https://grimler.se/termux-packages-24 stable/main arm bash arm 5.2.15-1 [859 kB]
Get:34 https://grimler.se/termux-packages-24 stable/main arm termux-keyring all 3.11 [37.2 kB]
Get:35 https://grimler.se/termux-packages-24 stable/main arm termux-licenses all 2.0-3 [52.2 kB]
Get:36 https://grimler.se/termux-packages-24 stable/main arm libgpg-error arm 1.47 [102 kB]
Get:37 https://grimler.se/termux-packages-24 stable/main arm libassuan arm 2.5.6 [68.6 kB]
Get:38 https://grimler.se/termux-packages-24 stable/main arm libgcrypt arm 1.10.2 [425 kB]
Get:39 https://grimler.se/termux-packages-24 stable/main arm gpgv arm 2.4.3 [165 kB]
Get:40 https://grimler.se/termux-packages-24 stable/main arm libevent arm 2.1.12-2 [190 kB]
Get:41 https://grimler.se/termux-packages-24 stable/main arm libexpat arm 2.5.0-1 [76.4 kB]
Get:42 https://grimler.se/termux-packages-24 stable/main arm libunistring arm 1.1 [517 kB]
Get:43 https://grimler.se/termux-packages-24 stable/main arm libidn2 arm 2.3.4 [100 kB]
Get:44 https://grimler.se/termux-packages-24 stable/main arm liblz4 arm 1.9.4 [87.9 kB]
Get:45 https://grimler.se/termux-packages-24 stable/main arm libnettle arm 3.9.1 [396 kB]
Get:46 https://grimler.se/termux-packages-24 stable/main arm xxhash arm 0.8.2 [75.4 kB]
Get:47 https://grimler.se/termux-packages-24 stable/main arm command-not-found arm 2.2.0-11 [79.2 kB]
Get:48 https://grimler.se/termux-packages-24 stable/main arm debianutils arm 5.8 [17.3 kB]
Get:49 https://grimler.se/termux-packages-24 stable/main arm dos2unix arm 7.5.0 [61.8 kB]
Get:50 https://grimler.se/termux-packages-24 stable/main arm ed arm 1.19 [37.6 kB]
Get:51 https://grimler.se/termux-packages-24 stable/main arm inetutils arm 2.4-1 [227 kB]
Get:52 https://grimler.se/termux-packages-24 stable/main arm libtirpc arm 1.3.3 [117 kB]
Get:53 https://grimler.se/termux-packages-24 stable/main arm lsof arm 4.98.0 [107 kB]
Get:54 https://grimler.se/termux-packages-24 stable/main arm nano arm 7.2 [209 kB]
Get:55 https://grimler.se/termux-packages-24 stable/main arm unzip arm 6.0-9 [114 kB]
Fetched 13.4 MB in 6s (2181 kB/s)
(Reading database ... 4159 files and directories currently installed.)
Preparing to unpack .../archives/libiconv_1.17_arm.deb ...
Unpacking libiconv (1.17) over (1.16-3) ...
Setting up libiconv (1.17) ...
(Reading database ... 4160 files and directories currently installed.)
Preparing to unpack .../libandroid-support_28-3_arm.deb ...
Unpacking libandroid-support (28-3) over (28-2) ...
Setting up libandroid-support (28-3) ...
(Reading database ... 4160 files and directories currently installed.)
Preparing to unpack .../ncurses_6.4.20230527_arm.deb ...
Unpacking ncurses (6.4.20230527) over (6.3) ...
Setting up ncurses (6.4.20230527) ...
(Reading database ... 4158 files and directories currently installed.)
Preparing to unpack .../readline_8.2.1_arm.deb ...
Unpacking readline (8.2.1) over (8.1.1) ...
aSetting up readline (8.2.1) ...
(Reading database ... 4160 files and directories currently installed.)
Preparing to unpack .../termux-am-socket_1.5.0_arm.deb ...
Unpacking termux-am-socket (1.5.0) over (1.3.0) ...
Setting up termux-am-socket (1.5.0) ...
(Reading database ... 4160 files and directories currently installed.)
Preparing to unpack .../archives/libc++_25c_arm.deb ...
Unpacking libc++ (25c) over (23b-3) ...
Setting up libc++ (25c) ...
(Reading database ... 4160 files and directories currently installed.)
Preparing to unpack .../libgmp_6.2.1-2_arm.deb ...
Unpacking libgmp (6.2.1-2) over (6.2.1-1) ...
Setting up libgmp (6.2.1-2) ...
(Reading database ... 4160 files and directories currently installed.)
Preparing to unpack .../archives/coreutils_9.3_arm.deb ...
Unpacking coreutils (9.3) over (9.1) ...
apSetting up coreutils (9.3) ...
(Reading database ... 4160 files and directories currently installed.)
Preparing to unpack .../ca-certificates_1%3a2023.05.30_all.deb ...
tUnpacking ca-certificates (1:2023.05.30) over (1:2022.03.29) ...
Setting up ca-certificates (1:2023.05.30) ...
(Reading database ... 4155 files and directories currently installed.)
Preparing to unpack .../archives/zlib_1.2.13_arm.deb ...
Unpacking zlib (1.2.13) over (1.2.12) ...
Setting up zlib (1.2.13) ...
(Reading database ... 4155 files and directories currently installed.)
Preparing to unpack .../openssl_1%3a3.1.2_arm.deb ...
Unpacking openssl (1:3.1.2) over (3.0.2) ...
Setting up openssl (1:3.1.2) ...

Configuration file '/data/data/com.termux/files/usr/etc/tls/openssl.cnf'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** openssl.cnf (Y/I/N/O/D/Z) [default=N] ? apt-get update

Configuration file '/data/data/com.termux/files/usr/etc/tls/openssl.cnf'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** openssl.cnf (Y/I/N/O/D/Z) [default=N] ? y
Installing new version of config file /data/data/com.termux/files/usr/etc/tls/openssl.cnf ...
(Reading database ... 4155 files and directories currently installed.)
Preparing to unpack .../libnghttp2_1.55.1_arm.deb ...
Unpacking libnghttp2 (1.55.1) over (1.47.0) ...
Setting up libnghttp2 (1.55.1) ...
(Reading database ... 4155 files and directories currently installed.)
Preparing to unpack .../libssh2_1.11.0_arm.deb ...
Unpacking libssh2 (1.11.0) over (1.10.0-2) ...
Setting up libssh2 (1.11.0) ...
(Reading database ... 4167 files and directories currently installed.)
Preparing to unpack .../archives/libcurl_8.2.1_arm.deb ...
Unpacking libcurl (8.2.1) over (7.83.0) ...
pkpSetting up libcurl (8.2.1) ...
(Reading database ... 4181 files and directories currently installed.)
Preparing to unpack .../archives/curl_8.2.1_arm.deb ...
Unpacking curl (8.2.1) over (7.83.0) ...
pSetting up curl (8.2.1) ...
(Reading database ... 4181 files and directories currently installed.)
Preparing to unpack .../archives/dash_0.5.12_arm.deb ...
Unpacking dash (0.5.12) over (0.5.11.5-1) ...
Setting up dash (0.5.12) ...
(Reading database ... 4181 files and directories currently installed.)
Preparing to unpack .../diffutils_3.10_arm.deb ...
Unpacking diffutils (3.10) over (3.8) ...
Setting up diffutils (3.10) ...
(Reading database ... 4181 files and directories currently installed.)
Preparing to unpack .../findutils_4.9.0-2_arm.deb ...
Unpacking findutils (4.9.0-2) over (4.9.0-1) ...
Setting up findutils (4.9.0-2) ...
(Reading database ... 4181 files and directories currently installed.)
Preparing to unpack .../libmpfr_4.2.0-p9-0_arm.deb ...
Unpacking libmpfr (4.2.0-p9-0) over (4.1.0-1) ...
Setting up libmpfr (4.2.0-p9-0) ...
(Reading database ... 4181 files and directories currently installed.)
Preparing to unpack .../archives/gawk_5.2.2_arm.deb ...
Unpacking gawk (5.2.2) over (5.1.1-1) ...
Setting up gawk (5.2.2) ...
(Reading database ... 4192 files and directories currently installed.)
Preparing to unpack .../archives/pcre2_10.42_arm.deb ...
Unpacking pcre2 (10.42) over (10.40) ...
pkp-Setting up pcre2 (10.42) ...
(Reading database ... 4194 files and directories currently installed.)
Preparing to unpack .../apt/archives/grep_3.11_arm.deb ...
Unpacking grep (3.11) over (3.7-2) ...
Setting up grep (3.11) ...
(Reading database ... 4192 files and directories currently installed.)
Preparing to unpack .../archives/gzip_1.12-1_arm.deb ...
Unpacking gzip (1.12-1) over (1.12) ...
Setting up gzip (1.12-1) ...
(Reading database ... 4192 files and directories currently installed.)
Preparing to unpack .../archives/less_633-1_arm.deb ...
Unpacking less (633-1) over (590) ...
Setting up less (633-1) ...
(Reading database ... 4192 files and directories currently installed.)
Preparing to unpack .../procps_3.3.17-2_arm.deb ...
Unpacking procps (3.3.17-2) over (3.3.17-1) ...
Setting up procps (3.3.17-2) ...
(Reading database ... 4192 files and directories currently installed.)
Preparing to unpack .../archives/psmisc_23.6-1_arm.deb ...
Unpacking psmisc (23.6-1) over (23.4) ...
Setting up psmisc (23.6-1) ...
(Reading database ... 4192 files and directories currently installed.)
Preparing to unpack .../apt/archives/sed_4.9-1_arm.deb ...
Unpacking sed (4.9-1) over (4.8-2) ...
Setting up sed (4.9-1) ...
(Reading database ... 4192 files and directories currently installed.)
Preparing to unpack .../apt/archives/tar_1.35_arm.deb ...
Unpacking tar (1.35) over (1.34) ...
Setting up tar (1.35) ...
(Reading database ... 4193 files and directories currently installed.)
Preparing to unpack .../archives/liblzma_5.4.4_arm.deb ...
Unpacking liblzma (5.4.4) over (5.2.5-1) ...
Setting up liblzma (5.4.4) ...
(Reading database ... 4265 files and directories currently installed.)
Preparing to unpack .../xz-utils_5.4.4_arm.deb ...
Unpacking xz-utils (5.4.4) over (5.2.5-1) ...
Setting up xz-utils (5.4.4) ...
(Reading database ... 4265 files and directories currently installed.)
Preparing to unpack .../dialog_1.3-20230209-0_arm.deb ...
Unpacking dialog (1.3-20230209-0) over (1.3-20220117-0) ...
Setting up dialog (1.3-20230209-0) ...
(Reading database ... 4265 files and directories currently installed.)
Preparing to unpack .../termux-tools_1.38.5_all.deb ...
Unpacking termux-tools (1.38.5) over (0.175) ...
Setting up termux-tools (1.38.5) ...

Configuration file '/data/data/com.termux/files/usr/etc/motd'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** motd (Y/I/N/O/D/Z) [default=N] ? pkg upgrade-y && pkg update-y && pkg install nodejs-y && pkg install nodejs-its-&& pkg install ffmpeg-y && pkg install wget-y && pkg install git-y

Configuration file '/data/data/com.termux/files/usr/etc/motd'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** motd (Y/I/N/O/D/Z) [default=N] ? termux-setup-storage

Configuration file '/data/data/com.termux/files/usr/etc/motd'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** motd (Y/I/N/O/D/Z) [default=N] ? termux-setup-storage y

Configuration file '/data/data/com.termux/files/usr/etc/motd'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** motd (Y/I/N/O/D/Z) [default=N] ? o

**Comment by NuevaGeneracionALB** [comment]
!antifake 1
