### ISSUE TITLE
Comandos não funcionam direito na VPS

### ISSUE THREAD

**Issue by Tobiasx1** [NuevaGeneracionALB/aleatory-md#23]
Olá Aleatory, queria primeiramente agradecer por disponibilizar o bot pro pessoal administrar seus grupos. Eu queria pedir que pensasse um pouco mais nos usuários de vps pois todos os comandos de download na VPS não estão funcionando. Além disse eu adorei o sistema de golds mas ate que seria legal dar uma implementada e colocar coisas tipo profissões e etc bem RPG mesmo. Obrigado e um forte abraço!

**Comment by bronxys** [comment]
Veja este vídeo: https://youtube.com/shorts/RZbOrf1d40U?si=dJXkQcKeRe5mRm6f

**Comment by NuevaGeneracionALB** [comment]
Veja este vídeo: https://youtube.com/shorts/RZbOrf1d40U?si=dJXkQcKeRe5mRm6f
