### ISSUE TITLE
Desativar verificado dos menus

### ISSUE THREAD

**Issue by Brasil150** [NuevaGeneracionALB/aleatory-md#3]
Mesmo marcando "verificado": false ainda continua vindo com verificado
![5d421566-95e0-4fdc-b758-9a8927674944](https://user-images.githubusercontent.com/55663598/156448768-5f234b36-3dc0-4db2-9a67-ed5ef0e20a4a.jpg)

**Comment by NuevaGeneracionALB** [comment]
O multi-device não contem esta opção.
